export const modelos3d = [
  {
    id: 1,
    nome: "Batmóvel",
    categoria: "Veículo Tático",
    descricao: "Veículo blindado de alta performance com tecnologia Wayne",
    arquivo: "/modelos3d/batmobile.glb",
    thumbnail: "/thumbnails/batmobile.png",
    cor: "#1a1a1a",
    nivelMinimo: "admin",
  },

  {
    id: 2,
    nome: "Bat-Wing",
    categoria: "Veículo Aéreo",
    descricao: "Aeronave de combate e reconhecimento",
    arquivo: "/modelos3d/3d_batwing_batman_planespacecraft.glb",
    thumbnail: "/thumbnails/batwing.png",
    cor: "#0a0a0a",
    nivelMinimo: "admin",
  },
  {
    id: 3,
    nome: "Armadura do Batman",
    categoria: "Equipamento",
    descricao: "Armadura avançada com tecnologia Wayne",
    arquivo: "/modelos3d/batman_vs_superman_suit.glb",
    thumbnail: "/thumbnails/batman-suit.png",
    cor: "#1a1a2a",
    nivelMinimo: "admin",
  },
  {
    id: 4,
    nome: "Batarangue",
    categoria: "Gadget",
    descricao: "Dispositivo de arremesso multifuncional",
    arquivo: "/modelos3d/dc_batman_batarang.glb",
    thumbnail: "/thumbnails/batarang.png",
    cor: "#3a3a3a",
    nivelMinimo: "admin",
  },
  {
    id: 5,
    nome: "Console de Computador Grande",
    categoria: "Infraestrutura",
    descricao: "Sistema de computação principal da Batcaverna",
    arquivo: "/modelos3d/large-pc.glb",
    thumbnail: "/thumbnails/console-large.png",
    cor: "#00d4ff",
    nivelMinimo: "gerente",
  },
  {
    id: 6,
    nome: "Console de Computador Pequeno",
    categoria: "Infraestrutura",
    descricao: "Terminal de acesso secundário",
    arquivo: "/modelos3d/wall_computer_-_small.glb",
    thumbnail: "/thumbnails/console-small.png",
    cor: "#00d4ff",
    nivelMinimo: "gerente",
  },
  {
    id: 7,
    nome: "Drone de Segurança",
    categoria: "Segurança",
    descricao: "Drone autônomo para monitoramento perimetral",
    arquivo: "/modelos3d/security_drone.glb",
    thumbnail: "/thumbnails/security-drone.png",
    cor: "#00ff88",
    nivelMinimo: "gerente",
  },
  {
    id: 8,
    nome: "Drone Terrestre",
    categoria: "Segurança",
    descricao: "Drone de patrulha com câmeras de alta resolução",
    arquivo: "/modelos3d/police_drone.glb",
    thumbnail: "/thumbnails/police-drone.png",
    cor: "#00ff88",
    nivelMinimo: "gerente",
  },
  {
    id: 9,
    nome: "Drone Espião",
    categoria: "Segurança",
    descricao: "Drone multifuncional para diversas operações",
    arquivo: "/modelos3d/drone.glb",
    thumbnail: "/thumbnails/drone.png",
    cor: "#00d4ff",
    nivelMinimo: "funcionario",
  },
  {
    id: 10,
    nome: "Armadilha Sci-Fi",
    categoria: "Segurança",
    descricao: "Sistema de contenção avançado",
    arquivo: "/modelos3d/sci_fi_trap_game_ready.glb",
    thumbnail: "/thumbnails/trap.png",
    cor: "#ff6b35",
    nivelMinimo: "gerente",
  },
]
